import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
export const Input = React.forwardRef(({ label, error, helpText, icon, className = '', ...props }, ref) => (_jsxs("div", { className: "flex flex-col gap-2", children: [label && (_jsxs("label", { className: "font-sans text-sm font-medium text-neutral-text", children: [label, props.required && _jsx("span", { className: "text-semantic-error ml-1", children: "*" })] })), _jsxs("div", { className: "relative", children: [icon && _jsx("span", { className: "absolute left-3 top-3 text-neutral-text-muted", children: icon }), _jsx("input", { ref: ref, className: `input ${icon ? 'pl-10' : ''} ${error ? 'border-semantic-error' : ''} ${className}`, ...props })] }), error && _jsx("p", { className: "text-xs text-semantic-error font-medium", children: error }), helpText && !error && _jsx("p", { className: "text-xs text-neutral-text-muted", children: helpText })] })));
Input.displayName = 'Input';
export const TextArea = React.forwardRef(({ label, error, helpText, className = '', ...props }, ref) => (_jsxs("div", { className: "flex flex-col gap-2", children: [label && (_jsxs("label", { className: "font-sans text-sm font-medium text-neutral-text", children: [label, props.required && _jsx("span", { className: "text-semantic-error ml-1", children: "*" })] })), _jsx("textarea", { ref: ref, className: `input resize-vertical min-h-[120px] ${error ? 'border-semantic-error' : ''} ${className}`, ...props }), error && _jsx("p", { className: "text-xs text-semantic-error font-medium", children: error }), helpText && !error && _jsx("p", { className: "text-xs text-neutral-text-muted", children: helpText })] })));
TextArea.displayName = 'TextArea';
export const Select = React.forwardRef(({ label, error, options, className = '', ...props }, ref) => (_jsxs("div", { className: "flex flex-col gap-2", children: [label && (_jsx("label", { className: "font-sans text-sm font-medium text-neutral-text", children: label })), _jsxs("select", { ref: ref, className: `input cursor-pointer ${error ? 'border-semantic-error' : ''} ${className}`, ...props, children: [_jsx("option", { value: "", children: "Select an option" }), options.map((opt) => (_jsx("option", { value: opt.value, children: opt.label }, opt.value)))] }), error && _jsx("p", { className: "text-xs text-semantic-error font-medium", children: error })] })));
Select.displayName = 'Select';
export const Checkbox = React.forwardRef(({ label, className = '', ...props }, ref) => (_jsxs("label", { className: "flex items-center gap-2 cursor-pointer", children: [_jsx("input", { ref: ref, type: "checkbox", className: `w-4 h-4 rounded cursor-pointer border border-neutral-border focus:ring-2 focus:ring-primary-800 ${className}`, ...props }), label && _jsx("span", { className: "text-sm text-neutral-text", children: label })] })));
Checkbox.displayName = 'Checkbox';
//# sourceMappingURL=Input.js.map